[Meetings] Use es-module lodash for import correctness across servers (Recidiviz/recidiviz-dashboards#11335)
## Description of the change

I updated a few of the import paths for `lodash` which ended up breaking
when run in the production javascript bundle. This updates to use
`lodash-es` so that we can use es-module imports of the various lodash
utils.

Curious if y'all can think of any kind of test coverage that could have
caught this class of error (incompatibility between built js + `node`
and the dev ts + `vite-node`)? cc @macfarlandian maybe?

```
SyntaxError: The requested module 'lodash' does not provide an export named 'template'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:213:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:320:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

```
DEFAULT 2026-01-15T20:20:58.221284Z Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/app/node_modules/lodash/has' imported from /usr/src/app/main.js
DEFAULT 2026-01-15T20:20:58.221302Z Did you mean to import "lodash/has.js"?
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
| --------------------------- |
---------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

Resolve Sentry issue:
Fixes RECIDIVIZ-PULSE-DASHBOARD-[XXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the
Readme](https://github.com/Recidiviz/recidiviz-dashboards#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: e9ecb5c74764e65dbffefd71ce0a5b5aed109a09